[workspace]
members = [
    "crates/model",
    "crates/smql-syntax",
    "crates/planner",
    "crates/connectors",
    "crates/engine-core",
    "crates/engine-config",
    "crates/engine-runtime",
    "crates/engine-processing",
    "crates/engine-tests",
    "crates/expression-engine",
    "crates/cli",
]

resolver = "2"
