[workspace]
members = [
    "adapters/csv",
    "adapters/sql/mysql",
    "adapters/sql/postgres",
    "adapters/sql/sql_adapter",
    "cli",
    "data-model",
    "engine",
    "query-builder",
    "smql",
]

resolver = "2"
