[package]
name = "query-builder"
version = "0.1.0"
edition = "2024"

[dependencies]
data-model = { path = "../data-model" }

serde = "1.0.217"
serde_json = "1.0.138"
async-trait = "0.1.86"
chrono-tz = "0.10.4"
